name: cass_rtd
dependencies:
  - flake8
  - pytest
  - Pillow
  - arrow
  - requests
  - pip:
    - git+https://github.com/meraki-analytics/datapipelines
    - git+https://github.com/meraki-analytics/merakicommons
